version: '3.9'
services:
  database:
    image: postgres
    restart: always
    container_name: identity_database
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  db_ui:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "9990:9990"
      - "8080:8080"
  api:
    build: .
    ports:
      - "1323:1323"
    depends_on:
      database:
        condition: service_healthy
